# Generated by Django 5.1.1 on 2024-09-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_id',
            field=models.AutoField(default='not yet', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
